# Build dexed with JUCE buidls

trigger:
  - main

pr:
  - main

jobs:

  - job: Build
    strategy:
      matrix:
        mac:
          imageName: 'macos-latest'
          isMac: True
        win:
          imageName: 'windows-2022'
          isWindows: True
        lin:
          imageName: 'ubuntu-20.04'
          isLinux: True

    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        fetchDepth: 1


      - bash: |
          git submodule update --init --recursive
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DSST_PLUGININFRA_BUILD_TESTS=TRUE
          cmake --build build --config Release --target sst-all-tests
        displayName: Build Tests

      - bash: |
          cmake -Bbuild_ghc -DCMAKE_BUILD_TYPE=Debug -DSST_PLUGININFRA_FILESYSTEM_FORCE_GHC=ON
          cmake --build build_ghc --config Debug
        displayName: Build w GHC On (lin/mac only)
        condition: not(variables.isWindows)

      - bash: |
          cmake -Bbuild_pffs -DCMAKE_BUILD_TYPE=Debug -DSST_PLUGININFRA_FILESYSTEM_FORCE_PLATFORM=ON
          cmake --build build_pffs --config Debug
        displayName: Build w Platform FS On

      - bash: |
          pushd ./build/test-binary 
          ./sst-plugininfra-tests
          ./sst-tixml-tests
          ./dumppaths
        displayName: Run tests with cmake
